honeycombio/honeycomb-opentelemetry-node

.circleci/config.yml
.github/workflows/validate-pr-title.yml

The publish command requires `--access public` to be specified if a package is being published as a scoped package
- Updated the publish command
- Removed `pull_request_target` from the validate PR title check
- We have a [published package](https://www.npmjs.com/package/@honeycombio/opentelemetry-node)!

ci: update publish setup command

---

examples/hello-node-express/index.js
smoke-tests/smoke-sdk-grpc.bats
smoke-tests/smoke-sdk-http.bats

- Closes #105 
- Adds usage of baggage to hello-world-express example app.
- Adds smoke test expectations that key/values in baggage appear on child spans from within that context.
- Run the smoke tests!

test: add smoky expectations for BaggageSpanProcessor

---

DEVELOPING.md
package-lock.json
package.json

When installing in a new app, version conflicts caused the instrumentation to not work properly.
More investigation may be needed to help reduce conflicts in the future, but right now it seems that the most reliable usage is to use more current versions and to have the same versions in our dependencies and in end user apps, especially for the `api` and `auto-instrumentations-node` packages.
```text
"@opentelemetry/api": "^1.2.0", --> "^1.3.0"
"@opentelemetry/exporter-trace-otlp-grpc": "^0.33.0", --> "^0.34.0"
"@opentelemetry/exporter-trace-otlp-proto": "^0.33.0", --> "^0.34.0"
"@opentelemetry/resources": "^1.7.0", --> "^1.8.0"
"@opentelemetry/sdk-node": "^0.33.0", --> "^0.34.0"
"@opentelemetry/sdk-trace-base": "^1.7.0",--> "^1.8.0"
```
Also, notes were added into `DEVELOPING.md` about how …

maint: update opentelemetry dependencies

---

src/honeycomb-options.ts
test/honeycomb-options.test.ts

This lets you get a strongly-typed protocol type when you're using typescript but still supports the stringy-wingy kind as well.
```ts
const sdk = new HoneycombSdk({
protocol: OtlpProtocolKind.Grpc
});
```
And also:
```js
const sdk = new HoneycombSdk({
protocol: 'grpc'
});
```

feat: support enum-style protocol specification

---

examples/hello-node-express-ts/index.ts
examples/hello-node-express-ts/instrumentation.ts
src/index.ts

Exposes the `HoneycombOptions` type created in the distro that extends the OTel Node SDK config options. Exposing this type allows users to type check their config. TS / linters will be able to pick up if an incorrect config option is used.
- Export `HoneycombOptions` type
- Update TS example with typed config object
- Update TS example with some more types from OTel
- Try passing in a key to the config object in the example that isn't a part of the `HoneycombOptions` type, TS won't  compile and there should be linter warnings.

feat: Export `HoneycombOptions` type

---

.github/workflows/validate-pr-title.yml

Adds a better error message when the PR title conventional commit check fails. We'll use this PR as the main PR to review before applying it to the other repos.
- If the conventional commit check for PR titles fails, a comment appears on the PR with a friendly error message
- Once the title has been updated, the comment is deleted
- Added an option to ignore PR title validation for PRs with the label `type: dependencies` so that dependabot PRs are ignored.
1. Remove the conventional commit prefix from this PRs title
2. After the step fails, a comment should appear on the PR
3. Add the prefix back to the title
4. The comment should be deleted from the PR

ci: add PR comment for failed title check & ignore dependabot PRs

---

.eslintrc.js
examples/hello-node-express-ts/index.ts
examples/hello-node-express-ts/instrumentation.ts
examples/hello-node-express-ts/package-lock.json
examples/hello-node-express-ts/package.json
package-lock.json
package.json
src/exporter-utils.ts
src/honeycomb-options.ts
src/http-proto-metrics-exporter.ts
src/index.ts
src/opentelemetry-node.ts
test/exporter-utils.test.ts
test/http-proto-metrics-exporter.test.ts
test/setup-jest.ts

- Closes #126 
- add http/proto metrics exporter 
- only enable metrics if `metricsDataset` is set
- run the example express typescript app and it should export metrics

feat: Add metrics supprt for http/proto

---

.github/dependabot.yml

Our dependabot PRs are failing CI checks because of the PR title validation check. Instead of getting the PR title validation check to ignore dependabot PRs, I thought it would be better to add the correct semantic prefix to dependabot PRs instead.
- Updates https://github.com/honeycombio/telemetry-team/issues/389
- Adds semantic prefix `maint` to all dependabot commits / PRs
Unfortunately, it doesn't seem like we can validate dependabot config changes without merging them in according to [this issue](https://github.com/dependabot/dependabot-core/issues/4605).
I think this should work as expected based on:
- [The dependabot docs for `commit-message`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-messa …

fix: add semantic commit prefix to dependabot PRs

---

.github/dependabot.yml

In #131, there was a config error which this PR fixes.
- `include_scope: true` --> `include: "scope"`
The [docs reference the more up to date config ](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message)option for including scope.

fix: dependabot config for scope

---

examples/hello-node-express-ts/index.ts
examples/hello-node-express-ts/package-lock.json
examples/hello-node-express-ts/package.json
examples/hello-node-express/index.js
examples/hello-node-express/package-lock.json
examples/hello-node-express/package.json
smoke-tests/docker-compose.yml
smoke-tests/smoke-sdk-http-ts.bats
smoke-tests/smoke-sdk-http.bats

- Closes #130 
- add metrics to JS express app (already added to TS app)
- update counter to use "sheep" because we use it in other distros and smoke test for it ¯\_(ツ)_/¯
- remove metric interval from smoke tests (this caused issues with dotnet smoke testing, may be unnecessary)
- remove unused metric exporter package from our experiment when adding metrics exporter
smoke tests pass!
If you run it locally you should see the output in `smoke-tests/collector/data-results/data-app-sdk-http-ts.json` and `smoke-tests/collector/data-results/data-app-sdk-http` that includes `resourceMetrics`.
In CircleCI, the data is also saved in [artifacts](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-node/410/workflows/35504d47-5f63-4ffb-923d-3e8baaa41483/jobs/1629/artifacts). …

chore: add metrics tests to smoke tests

---

smoke-tests/docker-compose.yml
src/exporter-utils.ts
src/honeycomb-options.ts
test/honeycomb-options.test.ts
test/setup-jest.ts

- Closes #138 
- adds support for environment variables `OTEL_METRIC_EXPORT_INTERVAL` and `OTEL_METRIC_EXPORT_TIMEOUT`
- uses provided environment variables to set `exportIntervalMillis` and `exportTimeoutMillis` in metric exporter
Ideally these environment variables can/will be supported upstream, but in the meantime this should allow end users to configure timeout and interval behavior if needed. This is also used in our smoke tests to reduce test time.
Note: Validation logic to ensure the metric interval is higher than the metric timeout is handled upstream, and not included in this distro. If the values provided are not positive numbers, we'll simply leave as undefined (regular default behavior). The default values of 60000 and 30000 are set and used upstream.
Set these environment …

feat: make metrics export configurable

---

examples/hello-node-express-ts/README.md
examples/hello-node-express-ts/instrumentation.ts
examples/hello-node-express/README.md
examples/hello-node-express/index.js
src/opentelemetry-node.ts
src/resource-builder.ts
test/resource-builder.test.ts

- Closes #151 
- Changed the Resource builder to merge with any resources passed in when initializing the distro
- Added tests
- Added examples
1. Run the express or typescript express example
2. Set API keys so that data is being sent to Honeycomb (console spans don't seem to expand resource attributes and they show up as `resource: Resource { attributes: [Object] }`
3. Check in honeycomb to see if there's a `global.build_id` attribute on spans

fix: Allow user specified resource attributes

---

examples/hello-node-express-ts/index.ts
smoke-tests/smoke-sdk-grpc-ts.bats
smoke-tests/smoke-sdk-http-ts.bats

- confusion about how to add an observable gauge metric
- add new meter to typescript example app
- log nodejs runtime memory heap with observable gauge on new meter
- add meter checks to smoke tests
smoke tests should pass, and uploaded artifacts in circle should contain the new metrics
also see the metrics in honeycomb if running the app

maint: add observable gauge example

---

package-lock.json
package.json
src/honeycomb-options.ts

- Replaces #166 
- Bumps [prettier](https://github.com/prettier/prettier) from 2.8.1 to 2.8.4 
- Fix format based on prettier fail: add parentheses
- Fix up some typos
check-format passes in CI ([failed CI ](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-node/576/workflows/7b390df2-388c-45e1-8bb3-933dabca3334/jobs/2252)in dependabot PR)

maint: bump prettier from 2.8.1 to 2.8.4

---

.github/workflows/auto-merge.yml

- Lots of dependabots; auto-merging some subset of these may help ease some of the pain 
Add dependabot auto-merge workflow.
Current state of this file:
- `github.actor == 'dependabot[bot]'` means only run for PRs authored by Dependabot
- `(steps.metadata.outputs.dependency-type, 'direct:development')` means only run on dev dependencies
- `steps.metadata.outputs.update-type == 'version-update:semver-patch'` means only run for patch updates
- `gh pr review --approve "$PR_URL"` means approve PRs that match the above conditions
- `gh pr merge --auto --merge "$PR_URL"` means merge PRs that match the above conditions
After merging... In Insights / Dependency Graph / Dependabot, check for updates (or wait until the next weekly run). Any dev dependencies that have a patch update available should …

maint: add dependabot auto-merge workflow

---

.gitignore

- running smoke tests locally leaves you in a dirty git state
- `make smoke`
- `git status` should be clean

maint: ignore smoke test output

---

.gitignore
src/honeycomb-options.ts
test/honeycomb-options.test.ts

Adds a new option to allow skipping options validation. This is useful when the SDK is being used along with an OpenTelemetry Collector which configures API keys.
- Closes #201
- Add new skipOptionsValidation option, includes looking for new `HONEYCOMB_SKIP_OPTIONS_VALIDATION` env var -- default is `false`
- Add test to verify API key and dataset warnings are not seen when new option is set
- A debug message is logged if skip validation is true and debug is true

feat: Add option to skip options validation

---

src/opentelemetry-node.ts
test/opentelemetry-node.test.ts

- Closes #203
Allow users of `HoneycombSDK` to override the `NodeSDK` properties such as the `sampler`.
Pass in a `sampler` to the HoneycomSDK constructor and see it being used instead of the default `DeterministicSampler`.

fix: allow overriding node sdk properties

---

package-lock.json
package.json

We need to add `@opentelemetry/core` as a dependency because we are importing an interface and constant directly from it. I looked into whether these values are re-exported from the trace sdk or api packages and that doesn't seem to be the case. I think its okay for this package to depend on `@opentelemetry/core`, other exporter packages have to depend on it as well.
- Closes #206 
- Added `@opentelemetry/core` to `package.json` as a core dependency.
- `@opentelemetry/core` is listed is a direct dependency in `package-lock.json`
- Existing tests pass
- Install works on versions of yarn and pnpm

fix: add @opentelemetry/core as a dependency

---

src/honeycomb-options.ts
test/honeycomb-options.test.ts

Adds a warning if a custom sampler is provided. There are some pitfalls with providing a custom sampler if the `sampleRate` is non-deterministic.
- Added a warning if `sampler` option is provided by the user
- Unit tests pass 
- Test it out by adding a custom sampler to the `sampler` property in a test app.

maint: add custom sampler warning

---

.github/dependabot.yml

- otel dependencies should generally be updated together
- examples are not kept up to date with dependabot
- add dependabot grouping for `"@opentelemetry/*"`
- add dependabot for example directories
Dependabot should group PRs for OTel and should also open PRs for example apps. I considered some grouping in the example apps but those are smaller and primarily rely on the main package. Also the two different `"@opentelemetry/*"` packages are from two different repos (core and contrib) so they'll get released at different times.

maint: add dependabot groups and example deps

---

.github/release.yml

- we auto-generate release notes and if things aren't tagged they go into "other changes"
- dependencies and documentation PRs are generally considered maintenance, so if it has that label, it should get auto-categorized as maintenance on the auto-generated release notes

maint: add deps and docs to maintenance in release

---

src/composite-exporter.ts

I think this was some leftover copypasta. We actually do have this used for production since it's default-added in the HoneycombSdk when you instantiate it.

fix: composite exporter is for production use

---

.github/dependabot.yml

- lots of dependabots still
- group all example directory dependencies into one PR where possible (unfortunately they still have to be a PR per directory, unless we remove the package.json for each example and just use a shared one... which is an option 🤔 )
- group all dev dependencies into one PR
once this merges and dependabot checks for updates, the 4 open dev-dependency PRs should close and reopen in one PR

maint: more batching of dependabot groups

---

package-lock.json
package.json

- Follow-up from https://github.com/honeycombio/honeycomb-opentelemetry-node/issues/293#issuecomment-2002328040
- Use caret for versioning on API dependency, allowing for newer minor versions
Using this package `@honeycombio/opentelemetry-node` with upstream packages should have minimal version conflicts. The more restrictive version ranges (tilde instead of caret) were initially set because of breaking changes across different packages that affected end users, and the hope with the change was to minimize incompatibilities. However, the API range may have been too restrictive - perhaps we can adjust this and see if we need to ease up on others as well?

fix: ease restriction on api version

---

.github/dependabot.yml

- dependabot had wrong (old) team for reviewers
- updated dependabot file to set pipeline-team as reviewers
new dependabot PRs should properly assign pipeline team as reviewers

chore: update team for dependabot review
